---
- hosts: all
  become_user: root 
  tasks:
    - name: run echo command
      command: /bin/echo hello sammy
  roles:
     - { role: ansible-role-cloudwatch, become: yes } 
     - { role: debops.ntp, become: yes }

